apiVersion: v2
name: wayli
description: A privacy-first location analysis and trip tracking application
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 2.3.0-rc.4

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are expected to follow Semantic Versioning (https://semver.org/)
# This will be automatically updated by CI/CD pipeline after each release
appVersion: "v2.3.0-rc.5"

maintainers:
  - name: nimbleflux
    url: https://github.com/nimbleflux/wayli

home: https://github.com/nimbleflux/wayli
sources:
  - https://github.com/nimbleflux/wayli

keywords:
  - location
  - tracking
  - privacy
  - trip-analysis
  - gps

dependencies:
  - name: fluxbase
    version: '2026.8.4'
    repository: 'oci://ghcr.io/nimbleflux/charts'
    condition: fluxbase.enabled

annotations:
  artifacthub.io/prerelease: "true"
