-- Wayli database extensions
--
-- Extensions that Wayli requires but Fluxbase's bootstrap does NOT enable.
-- Fluxbase's bootstrap (run on every server startup) already enables:
--   uuid-ossp, pgcrypto, pg_trgm, btree_gin, vector, postgres_fdw
--
-- These are enabled via the Fluxbase extensions API (`fluxbase extensions enable`)
-- in sync:schema / startup.sh, NOT via raw SQL. This ensures they're tracked in
-- platform.enabled_extensions and visible in the admin UI.
--
-- PostGIS provides the geography/geometry types and ST_* functions used by
-- tracker_data.location (geography) and the place_visits location indexes.
--
-- To enable manually:
--   fluxbase extensions enable postgis
--   fluxbase extensions enable postgis_topology
