-- 078_transport_mode.up.sql
--
-- Persist transport-mode detection results on tracker_data + incremental
-- watermark for the detect-transport-mode background job.
--
-- Transport mode used to be recomputed client-side on every Location Data page
-- load (expensive at >100k points, no shared source of truth). It is now
-- computed once by the Deno job (HMM/Viterbi, web/src/lib/services/transport-mode)
-- and stored here. The page reads stored values and falls back to live
-- detection only for points not yet processed.

-- =============================================================================
-- Step 1: Add transport-mode columns to tracker_data
-- =============================================================================

ALTER TABLE "public"."tracker_data"
    ADD COLUMN IF NOT EXISTS "transport_mode" text,
    ADD COLUMN IF NOT EXISTS "detection_reason" text,
    ADD COLUMN IF NOT EXISTS "transport_mode_confidence" numeric(4, 3);

COMMENT ON COLUMN "public"."tracker_data"."transport_mode" IS
    'Detected transport mode: stationary|walking|cycling|car|train|airplane. NULL when not yet processed by the detect-transport-mode job.';
COMMENT ON COLUMN "public"."tracker_data"."detection_reason" IS
    'Machine-readable reason key for the detected transport_mode (see TransportDetectionReason labels in the UI).';
COMMENT ON COLUMN "public"."tracker_data"."transport_mode_confidence" IS
    'HMM emission confidence in [0,1] for the detected transport_mode.';

-- Partial index: only rows that have been processed carry a mode, so filtering
-- "unprocessed" (NULL) points is cheap for both the job and the page fallback.
CREATE INDEX IF NOT EXISTS "idx_tracker_data_transport_mode"
    ON "public"."tracker_data" ("user_id", "transport_mode")
    WHERE "transport_mode" IS NOT NULL;

-- =============================================================================
-- Step 2: Watermark table for the incremental detect-transport-mode job.
--         Cloned from place_visits_state (migration 017): per-user watermark,
--         NULL user_id = global state.
-- =============================================================================

CREATE TABLE IF NOT EXISTS "public"."transport_mode_state" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    "last_processed_at" timestamp with time zone,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "transport_mode_state_user_unique" UNIQUE (user_id)
);

INSERT INTO "public"."transport_mode_state" (user_id, last_processed_at)
VALUES (NULL, NULL)
ON CONFLICT (user_id) DO NOTHING;

CREATE INDEX IF NOT EXISTS "transport_mode_state_user_id_idx"
    ON "public"."transport_mode_state" (user_id);

COMMENT ON TABLE "public"."transport_mode_state" IS
    'Incremental watermark for the detect-transport-mode job. last_processed_at is exclusive; the job resumes from last_processed_at - LOOKBACK (1h) to re-decode the tail of the previous segment.';

-- Enable RLS + policies mirroring tracker_data (owner + service_role + admin).
ALTER TABLE "public"."transport_mode_state" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own transport_mode_state"
    ON "public"."transport_mode_state" FOR SELECT TO "authenticated"
    USING (auth.uid() = user_id);

CREATE POLICY "Service role has full access to transport_mode_state"
    ON "public"."transport_mode_state" FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY "Admin users have full access to transport_mode_state"
    ON "public"."transport_mode_state" FOR ALL TO "authenticated"
    USING (auth.jwt()->>'role' = 'admin') WITH CHECK (auth.jwt()->>'role' = 'admin');

-- =============================================================================
-- Step 3: Recreate my_tracker_data to expose the new columns.
--         Must DROP before CREATE (SQLSTATE 42P16: CREATE OR REPLACE VIEW
--         cannot change the column list). Dropping loses grants, so re-issue.
-- =============================================================================

DROP VIEW IF EXISTS "public"."my_tracker_data";

CREATE VIEW "public"."my_tracker_data"
WITH (security_barrier = true, security_invoker = true)
AS
SELECT
    recorded_at,
    ST_X(location::geometry) as longitude,
    ST_Y(location::geometry) as latitude,
    country_code,
    geocode,
    accuracy,
    transport_mode,
    detection_reason,
    transport_mode_confidence,
    created_at,
    recorded_at as started_at
FROM "public"."tracker_data"
WHERE user_id = auth.uid();

COMMENT ON VIEW "public"."my_tracker_data" IS 'Secure view of tracker_data filtered to current user. Use this for LLM queries.';

GRANT SELECT ON "public"."my_tracker_data" TO "authenticated";

-- =============================================================================
-- Step 4: Grants for transport_mode_state (table-level, mirrors tracker_data)
-- =============================================================================

GRANT SELECT ON "public"."transport_mode_state" TO "authenticated";
GRANT ALL ON "public"."transport_mode_state" TO "service_role";
