-- 079_tracker_daily_activity.up.sql
--
-- Cached per-day aggregation of tracker_data for the activity calendar.
-- Mirrors the place_visits incremental pattern (migration 017): a regular
-- table + watermark, refreshed by the refresh-daily-activity job. This makes
-- the activity_calendar RPC a sub-10ms indexed read instead of a full-table
-- aggregation that times out on cold caches.

-- =============================================================================
-- Step 1: tracker_daily_activity — one row per (user, day)
-- =============================================================================

CREATE TABLE IF NOT EXISTS "public"."tracker_daily_activity" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "day" date NOT NULL,
    "distance" numeric(12,2) DEFAULT 0,
    "time_spent" numeric(12,2) DEFAULT 0,
    "points" integer DEFAULT 0,
    "updated_at" timestamptz DEFAULT now(),
    CONSTRAINT "tracker_daily_activity_pkey" PRIMARY KEY ("user_id", "day")
);

COMMENT ON TABLE "public"."tracker_daily_activity" IS
    'Cached per-day distance/time/point-count aggregates from tracker_data. Refreshed incrementally by the refresh-daily-activity job. The activity_calendar RPC reads this instead of aggregating tracker_data live.';

CREATE INDEX IF NOT EXISTS "idx_tracker_daily_activity_user_day"
    ON "public"."tracker_daily_activity" ("user_id", "day");

-- =============================================================================
-- Step 2: Watermark table (clone of place_visits_state)
-- =============================================================================

CREATE TABLE IF NOT EXISTS "public"."tracker_daily_activity_state" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    "last_processed_at" timestamptz,
    "updated_at" timestamptz DEFAULT now(),
    CONSTRAINT "tracker_daily_activity_state_user_unique" UNIQUE (user_id)
);

INSERT INTO "public"."tracker_daily_activity_state" (user_id, last_processed_at)
VALUES (NULL, NULL)
ON CONFLICT (user_id) DO NOTHING;

CREATE INDEX IF NOT EXISTS "tracker_daily_activity_state_user_id_idx"
    ON "public"."tracker_daily_activity_state" (user_id);

COMMENT ON TABLE "public"."tracker_daily_activity_state" IS
    'Incremental watermark for the refresh-daily-activity job. last_processed_at is the cutoff up to which days have been aggregated.';

-- =============================================================================
-- Step 3: RLS + policies (mirror tracker_data / place_visits)
-- =============================================================================

ALTER TABLE "public"."tracker_daily_activity" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own daily activity"
    ON "public"."tracker_daily_activity" FOR SELECT TO "authenticated"
    USING (auth.uid() = user_id);

CREATE POLICY "Service role has full access to daily activity"
    ON "public"."tracker_daily_activity" FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY "Admin users have full access to daily activity"
    ON "public"."tracker_daily_activity" FOR ALL TO "authenticated"
    USING (auth.jwt()->>'role' = 'admin') WITH CHECK (auth.jwt()->>'role' = 'admin');

ALTER TABLE "public"."tracker_daily_activity_state" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own daily activity state"
    ON "public"."tracker_daily_activity_state" FOR SELECT TO "authenticated"
    USING (auth.uid() = user_id);

CREATE POLICY "Service role has full access to daily activity state"
    ON "public"."tracker_daily_activity_state" FOR ALL TO service_role
    USING (true) WITH CHECK (true);

-- =============================================================================
-- Step 4: Grants
-- =============================================================================

GRANT SELECT ON "public"."tracker_daily_activity" TO "authenticated";
GRANT ALL ON "public"."tracker_daily_activity" TO "service_role";
GRANT SELECT ON "public"."tracker_daily_activity_state" TO "authenticated";
GRANT ALL ON "public"."tracker_daily_activity_state" TO "service_role";
