// Shared enum for transport detection reasons
// This reduces bandwidth by sending enum keys instead of full text descriptions
export enum TransportDetectionReason {
  HIGH_VELOCITY_PLANE = 'HIGH_VELOCITY_PLANE',
  TRAIN_STATION_AND_SPEED = 'TRAIN_STATION_AND_SPEED',
  AIRPORT_AND_PLANE_SPEED = 'AIRPORT_AND_PLANE_SPEED',
  PLANE_SPEED_ONLY = 'PLANE_SPEED_ONLY',
  TRAIN_SPEED_ONLY = 'TRAIN_SPEED_ONLY',
  CAR_SPEED_ONLY = 'CAR_SPEED_ONLY',
  WALKING_SPEED_ONLY = 'WALKING_SPEED_ONLY',
  CYCLING_SPEED_ONLY = 'CYCLING_SPEED_ONLY',
  STATIONARY_SPEED_ONLY = 'STATIONARY_SPEED_ONLY',
  HIGHWAY_OR_MOTORWAY = 'HIGHWAY_OR_MOTORWAY',
  FAST_SEGMENT = 'FAST_SEGMENT',
  CONTINUITY_BROKEN = 'CONTINUITY_BROKEN',
  KEEP_CONTINUITY = 'KEEP_CONTINUITY',
  SUSPICIOUS_SEGMENT = 'SUSPICIOUS_SEGMENT',
  MIN_DURATION_NOT_MET = 'MIN_DURATION_NOT_MET',
  GEOGRAPHICALLY_IMPLAUSIBLE = 'GEOGRAPHICALLY_IMPLAUSIBLE',
  GOLF_COURSE_WALKING = 'GOLF_COURSE_WALKING',
  DEFAULT = 'DEFAULT'
}