{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wayli.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "wayli.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.annotations .Values.global.annotations }}
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
        {{- range .Values.ingress.extraHosts }}
        - {{ .name | quote }}
        {{- end }}
      {{- if .Values.ingress.selfSigned }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
      {{- else if .Values.ingress.secrets }}
      secretName: {{ (index .Values.ingress.secrets 0).name }}
      {{- else }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
      {{- end }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- toYaml .Values.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "wayli.fullname" . }}-web
                port:
                  number: {{ .Values.web.service.port }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ include "wayli.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
    {{- end }}
{{- end }}
