{{- if not .Values.supabase.global.supabase.auth.smtp.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wayli.fullname" . }}-smtp
  labels:
    {{- include "wayli.labels" . | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.supabase.global.supabase.auth.smtp.values }}
  {{ $.Values.supabase.global.supabase.auth.smtp.secretKeys.username }}: {{ .username | b64enc | quote }}
  {{ $.Values.supabase.global.supabase.auth.smtp.secretKeys.password }}: {{ .password | b64enc | quote }}
  {{- end }}
{{- end }}
