{{- if not .Values.global.pexels.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wayli.fullname" . }}-pexels
  labels:
    {{- include "wayli.labels" . | nindent 4 }}
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.global.pexels.values }}
  {{ $.Values.global.pexels.secretKeys.apiKey }}: {{ .apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
