{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wayli.fullname" . }}-worker
  labels:
    {{- include "wayli.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
  {{- with .Values.global.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "wayli.fullname" . }}-worker
  replicas: {{ .Values.worker.replicaCount }}
  {{- with .Values.worker.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  podManagementPolicy: {{ .Values.worker.podManagementPolicy }}
  selector:
    matchLabels:
      {{- include "wayli.selectorLabels.worker" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wayli.selectorLabels.worker" . | nindent 8 }}
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "wayli.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "wayli.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext:
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      {{- end }}
      {{- with .Values.worker.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.worker.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- with .Values.worker.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "wayli.initContainers.waitForInfrastructure" . | nindent 8 }}
      containers:
        - name: wayli-worker
          image: {{ include "wayli.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.containerSecurityContext.allowPrivilegeEscalation }}
            runAsNonRoot: {{ .Values.containerSecurityContext.runAsNonRoot }}
            runAsUser: {{ .Values.containerSecurityContext.runAsUser }}
            capabilities:
              drop:
                {{- range .Values.containerSecurityContext.capabilities.drop }}
                - {{ . }}
                {{- end }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: {{ .Values.worker.env.nodeEnv | quote }}
            - name: APP_MODE
              value: {{ .Values.worker.env.appMode | quote }}
            - name: SUPABASE_URL
              value: {{ include "wayli.supabase.url" . | quote }}
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "wayli.supabaseSecretName" . }}
                  key: {{ .Values.supabase.global.supabase.secretKeys.anonKey }}
            - name: SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "wayli.supabaseSecretName" . }}
                  key: {{ .Values.supabase.global.supabase.secretKeys.serviceRoleKey }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "wayli.supabaseSecretName" . }}
                  key: {{ .Values.supabase.global.supabase.secretKeys.jwtSecret }}
            - name: SUPABASE_DB_USERNAME
              value: {{ include "wayli.supabase.dbUser" . | quote }}
            - name: SUPABASE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "wayli.supabaseSecretName" . }}
                  key: {{ .Values.supabase.db.postgres.secretKeys.userPasswordKey }}
            - name: INTERNAL_SUPABASE_URL
              value: "http://{{ include "wayli.supabase.kongHost" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ include "wayli.supabase.kongPort" . }}"
            - name: WORKER_SUPABASE_URL
              value: "http://{{ include "wayli.supabase.kongHost" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ include "wayli.supabase.kongPort" . }}"
            - name: PUBLIC_SUPABASE_URL
              value: {{ include "wayli.supabase.url" . | quote }}
            - name: NOMINATIM_ENDPOINT
              value: {{ .Values.worker.env.nominatim.endpoint | quote }}
            - name: PEXELS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "wayli.pexelsSecretName" . }}
                  key: {{ .Values.global.pexels.secretKeys.apiKey }}
            {{- if .Values.worker.extraEnvVars }}
            {{- toYaml .Values.worker.extraEnvVars | nindent 12 }}
            {{- end }}
          {{- if or .Values.worker.extraEnvVarsCM .Values.worker.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.worker.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.worker.extraEnvVarsCM }}
            {{- end }}
            {{- if .Values.worker.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.worker.extraEnvVarsSecret }}
            {{- end }}
          {{- end }}
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.lifecycleHooks }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.worker.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.worker.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.worker.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.worker.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      restartPolicy: Always
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
